# Generated by Django 4.2.11 on 2026-01-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = []
