# Generated by Django 4.2.11 on 2026-01-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "oc_lettings_site",
            "0002_alter_address_options_alter_profile_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letting",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Letting",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
